# Generated by Django 2.2.5 on 2019-09-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guest_capacity', models.SmallIntegerField()),
                ('bed_number', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('guest_capacity', 'bed_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodation.Accommodation')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodation.RoomType')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_quantity', models.SmallIntegerField()),
                ('guest_quantity', models.SmallIntegerField()),
                ('additional_request', models.TextField()),
                ('booking_date', models.DateField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.Accommodation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.Room')),
            ],
            options={
                'ordering': ('-booking_date',),
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='accommodation.AccommodationType'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='address.Address'),
        ),
    ]
